apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: public-ingress
  namespace: tickets-hall
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: tickets-hall.local
      http:
        paths:
          - path: /auth(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: auth-service
                port:
                  number: 80
          - path: /customers(/)(register)
            pathType: ImplementationSpecific
            backend:
              service:
                name: customers-service
                port:
                  number: 80
          - path: /events(/|$)(?!admin)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: events-service
                port:
                  number: 80
          - path: /categories(/|$)(?!admin)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: events-service
                port:
                  number: 80
          - path: /reservations(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: tickets-service
                port:
                  number: 80
          - path: /venues(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: venues-service
                port:
                  number: 80
          - path: /ticket-types(/|$)(?!admin)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: tickets-service
                port:
                  number: 80
          #   pathType: ImplementationSpecific
          #   backend:
          #     service:
          #       name: service-label
          #       port:
          #         number: 80
