apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: public-ingress
  namespace: tickets-hall
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - host: tickets-hall.local
      http:
        paths:
          - path: /(auth/public.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: auth-service
                port:
                  number: 80
          - path: /(customers/public.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: customers-service
                port:
                  number: 80
          - path: /(events/public.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: events-service
                port:
                  number: 80
          - path: /(categories/public.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: events-service
                port:
                  number: 80
          - path: /(ticket-types/public.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: events-service
                port:
                  number: 80
          - path: /(venues/public.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: venues-service
                port:
                  number: 80
          - path: /(attendance/public.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: attendance-service
                port:
                  number: 80
