apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: worker-ingress
  namespace: tickets-hall
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/auth-url: "http://auth-service.tickets-hall.svc.cluster.local/validate?role=WORKER"
    nginx.ingress.kubernetes.io/auth-method: "POST"
    nginx.ingress.kubernetes.io/auth-response-headers: "X-User-ID"
spec:
  ingressClassName: nginx
  rules:
    - host: tickets-hall.local
      http:
        paths:
          - path: /attendance(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: attendance-service
                port:
                  number: 80
