apiVersion: v1
kind: Service
metadata:
  name: postgres-notification
  namespace: tickets-hall
  labels:
    app: postgres-notification
spec:
  selector:
    app: postgres-notification
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
