apiVersion: v1
kind: Service
metadata:
  name: venues-service
  namespace: tickets-hall
  labels:
    app: venues-service
spec:
  selector:
    app: venues-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
