apiVersion: v1
kind: Service
metadata:
  name: attendance-service
  namespace: tickets-hall
  labels:
    app: attendance-service
spec:
  selector:
    app: attendance-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
