spring:
  datasource:
    url: jdbc:postgresql://localhost:5439/venues
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

app:
  rabbitmq:
    exchanges:
      worker: worker.exchange
    routing:
      workerCreated: worker.created
      workerUpdated: worker.updated
      workerDeleted: worker.deleted

server:
  port: 8080
  address: 0.0.0.0