server:
  port: 5000

spring:
  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/attendance?createDatabaseIfNotExist=true
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  
  # JPA/Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        '[format_sql]': true
  
  # Redis Configuration
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
  
  # RabbitMQ Configuration
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 2000ms
          max-attempts: 5
          max-interval: 10000ms
          multiplier: 2.0
        default-requeue-rejected: false
        acknowledge-mode: auto

# Application-specific RabbitMQ Configuration
app:
  rabbitmq:
    exchanges:
      user: user.exchange
      event: event.exchange
      ticket: ticket.exchange
#      ticketRetry: ticket.retry.exchange
    routing:
      userCreated: user.created
      eventCreated: event.created
      ticketCreated: ticket.created
    queues:
      userCreated: user.created.queue
      eventCreated: event.created.queue
      ticketCreated: ticket.created.queue
#        arguments:
#          x-dead-letter-exchange: ticket.retry.exchange
#          x-dead-letter-routing-key: ticket.created
#          x-message-ttl: 5000  # retry after 5 seconds
#    bindings:
#      - destination: user.created.queue
#        destinationType: queue
#        exchange: user.exchange
#        routingKey: user.created
#      - destination: event.created.queue
#        destinationType: queue
#        exchange: event.exchange
#        routingKey: event.created
#      - destination: ticket.created.queue
#        destinationType: queue
#        exchange: ticket.exchange
#        routingKey: ticket.created
#      - destination: ticket.created.queue
#        destinationType: queue
#        exchange: ticket.retry.exchange
#        routingKey: ticket.created

