server:
  port: 5000

spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s
  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5433/attendance?createDatabaseIfNotExist=true
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  
  # JPA/Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        '[format_sql]': true
  
  # Redis Configuration
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
  
  # RabbitMQ Configuration
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 2000ms
          max-attempts: 5
          max-interval: 10000ms
          multiplier: 2.0
        default-requeue-rejected: false
        acknowledge-mode: auto

# Application-specific RabbitMQ Configuration
app:
  rabbitmq:
    exchanges:
      user: user.exchange
      event: event.exchange
      ticket: ticket.exchange
      dead-letter: deadLetter.exchange
    routing:
      userCreated: user.created
      userUpdated: user.updated
      userDeleted: user.deleted
      eventCreated: event.created
      eventUpdated: event.updated
      eventDeleted: event.deleted
      ticketCreated: ticket.created
      ticketUpdated: ticket.updated
      ticketDeleted: ticket.deleted
      dead-letter: attendance.dead.letter
    queues:
      userCreated: attendance.user.created.queue
      userUpdated: attendance.user.updated.queue
      userDeleted: attendance.user.deleted.queue
      eventCreated: attendance.event.created.queue
      eventUpdated: attendance.event.updated.queue
      eventDeleted: attendance.event.deleted.queue
      ticketCreated: attendance.ticket.created.queue
      ticketUpdated: attendance.ticket.updated.queue
      ticketDeleted: attendance.ticket.deleted.queue
      dead-letter: attendance.final.dead.letter.queue

management:
  server:
    port: 1234
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      group:
        liveness:
          include: livenessState
        readiness:
          include: readinessState
      show-details: always
      validate-group-membership: false